### ISSUE TITLE
Changing default roles via Environment Variables

### ISSUE THREAD

**Issue by bzon** [Accenture/adop-nexus#1]
I'm trying to integrate this nexus container to an Active Directory LDAP. The current scenario is that we don't have an access the Active Directory server and add the default roles "nx-admin, nx-deployments, nx-developers" into it. With this, I'm required to follow their group naming standard. Example "devops-administrators" and not "nx-admin".

It would be nice if we can set the default roles via Environment Variables on container launch.
Example:
environment:
  LDAP_NEXUS_ADMIN_ROLE: "custom-admin-groupname"

**Comment by bzon** [comment]
PR submitted https://github.com/Accenture/adop-nexus/pull/2

**Comment by anton-kasperovich** [comment]
As pull request was merged, closed. Thank you @bzon .
