### ISSUE TITLE
Nexus 2.x and Scoped NPM packages: Can we upgrade to Nexus 3.x?

### ISSUE THREAD

**Issue by adamclerk** [Accenture/adop-nexus#8]
I'm using nexus to pull down npm dependencies and in npm 2.0.0 the feature of scoped packages was released. 

It looks like nexus started supporting this feature in v3.0.0 from this conversation here

https://issues.sonatype.org/browse/NEXUS-6857

Are there plans to update to nexus 3.0?

**Comment by nickdgriffin** [comment]
Hi Adam,

No active plans but we'd accept a PR for it assuming it worked (we'd test it out as well). We tend to only upgrade tools when there's a need to and we've just not had to cross that bridge yet for Nexus.

Thanks,
Nick

**Comment by nickdgriffin** [comment]
Hi Adam,

Just as an update, this is something we are working on at the moment.

Thanks,
Nick

**Comment by RobertNorthard** [comment]
Closing as Nexus has been upgraded to version sonatype/nexus3:3.12.1.
